accounts/urls.py
from django.urls import path,include
from .views import  adminv,manager,employee,common
urlpatterns=[
     path('', common.home, name='home'),
     path('employee/', include(([
           path('leave_form', employee.EmployeeCreateLeave, name='leave_form'),
     ], 'accounts'), namespace='employee')),
]

""" path('register/',views.register, name='register'),
     path('employee_register/',views.employee_register.as_view(), name='employee_register'),
     path('manager_register/',views.manager_register.as_view(), name='manager_register'),
     path('adminv_register/',views.adminv_register.as_view(), name='adminv_register'),
     path('login/',views.login_request, name='login'),
     path('logout/',views.logout_view, name='logout'),
"""     

demo_register/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts.views import  adminv,manager,employee,common

"""
urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
]"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', common.register, name='register'),
    path('accounts/register/manager/', manager.manager_register.as_view(), name='manager_register'),
    path('accounts/register/employee/', employee.employee_register.as_view(), name='employee_register'),
    path('accounts/register/employee/', adminv.adminv_register.as_view(), name='adminv_register'),
    path('login/',common.login_request, name='login'),
    path('logout/',common.logout_view, name='logout'),
]

pages/urls.py
from django.urls import path
from .import  views

urlpatterns=[
     path('',views.index, name='index'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_manager = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)
    is_adminV = models.BooleanField(default=False)

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

class Manager(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)

class Adminv(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)


class Leave(models.Model):
    sender=models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    reciever=models.ForeignKey(User, on_delete=models.CASCADE, related_name='reciever')
    start_date=models.DateField(auto_now=False, auto_now_add=False)
    end_date=models.DateField(auto_now=False, auto_now_add=False)
    application=models.TextField()
    torf=models.BooleanField(default=False)

pages/models.py
from django.db import models

# Create your models here.

accounts/views/adminv.py
from django.contrib.auth import login, logout,authenticate
from django.shortcuts import redirect, render
from django.contrib import messages
from django.views.generic import CreateView
from ..form import EmployeeSignUpForm,ManagerSignUpForm,AdminvSignUpForm
from django.contrib.auth.forms import AuthenticationForm
from ..models import User

def register(request):
    return render(request, '../templates/register.html')

class adminv_register(CreateView):
    model = User
    form_class = AdminvSignUpForm
    template_name = '../templates/adminv_register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')

accounts/views/common.py
from django.contrib.auth import login, logout,authenticate
from django.shortcuts import redirect, render
from django.contrib import messages
from django.views.generic import CreateView
from ..form import EmployeeSignUpForm,ManagerSignUpForm,AdminvSignUpForm
from django.contrib.auth.forms import AuthenticationForm
from ..models import User
from django.views.generic import TemplateView

def register(request):
    return render(request, '../templates/register.html')

def login_request(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None :
                login(request,user)
                return redirect('/')
            else:
                messages.error(request,"Invalid username or password")
        else:
                messages.error(request,"Invalid username or password")
    return render(request, '../templates/login.html',
    context={'form':AuthenticationForm()})

def logout_view(request):
    logout(request)
    return redirect('/')

def home(request):
    if request.user.is_authenticated:
        return render(request, '../templates/index.html')
    else:
        return render(request, '../templates/index.html')


"""
def register(request):
    return render(request, '../templates/register.html')

class manager_register(CreateView):
    model = User
    form_class = ManagerSignUpForm
    template_name = '../templates/manager_register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')

class employee_register(CreateView):
    model = User
    form_class = EmployeeSignUpForm
    template_name = '../templates/employee_register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')

class adminv_register(CreateView):
    model = User
    form_class = AdminvSignUpForm
    template_name = '../templates/adminv_register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')

def login_request(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None :
                login(request,user)
                return redirect('/')
            else:
                messages.error(request,"Invalid username or password")
        else:
                messages.error(request,"Invalid username or password")
    return render(request, '../templates/login.html',
    context={'form':AuthenticationForm()})

def logout_view(request):
    logout(request)
    return redirect('/')
"""

accounts/views/employee.py
from django.contrib.auth import login, logout,authenticate
from django.shortcuts import redirect, render
from django.contrib import messages
from django.views.generic import CreateView
from ..form import EmployeeSignUpForm,ManagerSignUpForm,AdminvSignUpForm,LeaveForm
from django.contrib.auth.forms import AuthenticationForm
from ..models import User,Leave

class employee_register(CreateView):
    model = User
    form_class = EmployeeSignUpForm
    template_name = '../templates/employee_register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')


def EmployeeCreateLeave(request):
    form = LeaveForm(request.user, request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            print('Saved form')
            form.save(request.user)
            form =LeaveForm(request.user)
    context = {
        'form': form,
        'user': request.user,
    }
    return render(request, 'leave_form.html',context)

accounts/views/manager.py
from django.contrib.auth import login, logout,authenticate
from django.shortcuts import redirect, render
from django.contrib import messages
from django.views.generic import CreateView
from ..form import EmployeeSignUpForm,ManagerSignUpForm,AdminvSignUpForm
from django.contrib.auth.forms import AuthenticationForm
from ..models import User

def register(request):
    return render(request, '../templates/register.html')

class manager_register(CreateView):
    model = User
    form_class = ManagerSignUpForm
    template_name = '../templates/manager_register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')

pages/views.py
from django.shortcuts import render

def index(request):
    return render(request, '../templates/index.html')

templates/adminv_register.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Demo Registration</title>
</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Register</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'adminv_register' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                             <input type="submit" value="Register" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>

templates/employee_register.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Demo Registration</title>
</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Register</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'employee_register' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                             <input type="submit" value="Register" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>

templates/index.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
label {
    display: block;
    font: 1rem 'Fira Sans', sans-serif;
}

input,
label {
    margin: .4rem 0;
}

</style>
</head>
<body>
{% if user.is_authenticated %}
    {% if user.is_manager %}
      <h1>manager page</h1>
      <h1>welcome {{user.username}} sir</h1>
      <a href="{% url 'register' %}">Register new user</a> <br>
      <a href="{% url 'logout' %}">Logout</a> <br>
    {% else%}
    {%if user.is_employee%}
      <h1>employee page</h1>
      <h1>welcome {{user.first_name}}</h1>
      <a href="{% url 'employee:leave_form' %}">APPLY Leave</a> <br>
      <a href="{% url 'logout' %}">Logout</a> <br>
        {%else%}
        <h1>admin portal<h1>
        <h1>welcome {{user.username}} sir</h1>
        <a href="{% url 'logout' %}">Logout</a> <br>
    {% endif %}
    {% endif %}
{% else %}
<h1>Welcome</h1>
<a href="{% url 'login' %}">Login</a> 
{% endif %}

</body>
</html>

templates/leave_form.html
{% load widget_tweaks %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class="container">
  <form action="",method="Post">
  <h3>Total leave:10<h3>
  {% for field in form.visible_fields %}
{% csrf_token %}
{{ field.label_tag }}
{% render_field field class="form-control"}
{% endfor %}
    <input type="submit" value="Submit">
  </form>
</div>
</body>
</html>

templates/login.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Demo Registration</title>
</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Login</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'login' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% if messages%}
                                      {% for message in messages %}
                                        <span style="color:red">{{ message }}</span>
                                      {% endfor %}
                                     {% endif %}
                         {% endfor %}
                         <br>
                             <input type="submit" value="Login" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>

templates/manager_register.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Demo Registration</title>
</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Register</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'manager_register' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                             <input type="submit" value="Register" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>

templates/register.html
<!DOCTYPE html>
{% if user.is_manager %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Demo Registration</title>
</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Demo Registration</h2>
                </div>
                <div class="card-body">
                    <div class="row">
                       <div class="col-lg-6">
                        <a type="button" class="btn btn-block" href="{% url 'employee_register' %}">I am a employee</a>
                       </div>
                       <div class="col-lg-6">
                        <a type="button" class="btn btn-block" href="{% url 'manager_register' %}">I am an manager</a>
                       </div>
                       <div class="col-lg-6">
                        <a type="button" class="btn btn-block" href="{% url 'adminv_register' %}">I am an admin</a>
                       </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
  {%else%}
  <h1>Manager can only create new users<h1>
{%endif%}

</body>
</html>